### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by loia5tqd001** [loia5tqd001/context-hook#1]
- [x] Provide an example for hooks with parameters
- [x] Provide an example for hooks with scope-level `Provider` (can be the same one as the item above)
- [x] Improve `displayName` for better working with React devtool
- [x] Write error handling/ handling for edge cases (Find `TODO:` comments in source code)
- [x] Write a comprehensive README
- [x] Remove unnecessary code from constate
- [x] Write examples on codesandbox 
- [ ] Write a more complex example with async, Form, Table
- [ ] Write examples on an `examples` folders with live deployed by vercel
- [ ] Make the examples more visually understandable (e.g: with border around each component)
- [ ] Pitch on Reddit, Hackernews, Twitter,...
- [ ] Write test
- [ ] 2 types of example: Code splitting and mornal
